export const SET_SELECT_VALUE = 'SET_SELECT_VALUE';
export const SET_SITE_INPUT_VALUE = 'SET_SITE_INPUT_VALUE';

export const SET_RADIO_INPUTS = 'SET_RADIO_INPUTS';
export const SET_OPTIONS_RESULT = 'SET_OPTIONS_RESULT';

export const SET_OPTIONS_INPUT_VALUE = 'SET_OPTIONS_INPUT_VALUE';

export const SET_MODAL_CONTENT = 'SET_MODAL_CONTENT';
export const SET_SHOW_MODAL = 'SET_SHOW_MODAL';

export const SET_COPY_LINK = 'SET_COPY_LINK';
export const SET_RESULT_LINK = 'SET_RESULT_LINK';